---
version: "3.4"
services:
  pg:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: social_network
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: