version: '3.8'
x-postgres-common:
  &postgres-common
  image: postgres:14-alpine
  user: postgres
  restart: 'no'
  healthcheck:
    test: 'pg_isready -U user --dbname=postgres'
    interval: 10s
    timeout: 5s
    retries: 5
  networks:
    - scnet
  cap_add:
    - NET_ADMIN

services:

  migrate:
    build: .
    image: social-network:local
    platform: linux/x86_64
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://user:password@pgmaster:5432/postgres?sslmode=disable
    command: [ "/goose", "-dir", "migrations", "up" ]
    depends_on:
      - pgmaster
    restart: on-failure
    networks:
      - scnet

  pgmaster:
    <<: *postgres-common
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command: |
      postgres 
      -c wal_level=replica 
      -c hot_standby=on 
      -c max_wal_senders=10 
      -c max_replication_slots=10 
      -c hot_standby_feedback=on
      -c synchronous_commit=on
      -c synchronous_standby_names='pgsync'
    volumes:
      - ./tools/00_init.sql:/docker-entrypoint-initdb.d/00_init.sql

  pgasync:
    <<: *postgres-common
    ports:
      - 5433:5432
    environment:
      PGUSER: replicator
      PGPASSWORD: replicator_password
    command: |
      bash -c "
      
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot_async --host=pgmaster --port=5432 | true
      do
        echo 'Waiting for primary to connect...'
        sleep 1s
      done
      echo 'Backup done, starting replica...'
      chmod 0700 /var/lib/postgresql/data
      
      sed -i 's/target_session_attrs=any/target_session_attrs=any application_name=pgasync/g' /var/lib/postgresql/data/postgresql.auto.conf

      postgres
      "
    depends_on:
      - pgmaster

  pgsync:
    <<: *postgres-common
    ports:
      - 5434:5432
    environment:
      PGUSER: replicator
      PGPASSWORD: replicator_password
    command: |
      bash -c "

      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot_sync --host=pgmaster --port=5432 | true
      do
        echo 'Waiting for primary to connect...'
        sleep 1s
      done
      echo 'Backup done, starting replica...'
      chmod 0700 /var/lib/postgresql/data

      sed -i 's/target_session_attrs=any/target_session_attrs=any application_name=pgsync/g' /var/lib/postgresql/data/postgresql.auto.conf

      postgres
      "
    depends_on:
      - pgmaster


networks:
  scnet:


#    docker exec -it --user=root social-network-pgasync-1 apk add iproute2
#   docker exec --user=root social-network-pgasync-1 tc qdisc add dev eth0 root netem delay 1000ms
