---
version: "3.4"
services:

  migrate:
    build: .
    image: social-network:local
    platform: linux/x86_64
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://admin:admin@db:5432/social-network?sslmode=disable
    command: [ "/goose", "-dir", "migrations", "up" ]
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: social-network
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: sc
    ports:
      - '27017:27017'
    volumes:
      - mongo-db:/data/db

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--experimental.plugins.traefik-request-id.modulename=github.com/ZeroGachis/traefik-request-id"
      - "--experimental.plugins.traefik-request-id.version=v0.1.5"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  backend:
    image: itimofeev/social-network:1.0.0
    environment:
      PG_REPOSITORY_DSN: postgres://social-network:wvGI7fofumA3yECJ9UO7NJaxQ@192.168.0.26:5432/social-network?sslmode=disable
    command: [ "/app/social-network" ]
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/api/v1/user`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    depends_on:
      - migrate

  dialogs:
    image: itimofeev/social-network:1.0.0
    environment:
      MONGO_REPOSITORY_DSB: mongodb://admin:admin@localhost:27017/sc
    command: [ "/app/dialogs" ]
    ports:
      - "8081:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/api/v1/dialogs`)"
      - "traefik.http.routers.whoami.entrypoints=web"

volumes:
  postgres-db:
  mongo-db: