---
version: "3.4"
services:

  migrate:
    build: .
    image: social-network:local
    platform: linux/x86_64
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://admin:admin@db:5432/social-network?sslmode=disable
    command: [ "/goose", "-dir", "migrations", "up" ]
    depends_on:
      - db
    restart: on-failure
    networks:
      - scnet

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: social-network
    ports:
      - '5432:5432'
    volumes:
      - ./tools/data/volumes/pgmaster:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - scnet

  db-async:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: social-network
    ports:
      - '6432:5432'
    volumes:
      - ./tools/data/volumes/pgasync:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - scnet

  db-sync:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '7432:5432'
    volumes:
      - ./tools/data/volumes/pgsync:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - scnet

  mongodb:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: sc
    ports:
      - '27017:27017'
    volumes:
      - mongo-db:/data/db
    networks:
      - scnet

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--log=true"
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--accesslog=true"
      - "--providers.file.filename=/etc/traefik/dynamic-traefik.yaml"
      - "--experimental.plugins.traefik-request-id.modulename=github.com/ZeroGachis/traefik-request-id"
      - "--experimental.plugins.traefik-request-id.version=v0.1.5"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./tools/traefik/config.yml:/etc/traefik/dynamic-traefik.yaml:ro"
    networks:
      - scnet

volumes:
  postgres-db:
  mongo-db:

networks:
  scnet:
    