### Register user
POST {{host}}/api/v1/user/register
Content-Type: application/json

{
  "first_name": "Hello",
  "second_name": "There",
  "birthdate": "2023-01-01",
  "biography": "biography",
  "city": "Moscow",
  "password": "123456"
}

### Get user by user_id
GET {{host}}/api/v1/user/get/20129b22-6dcb-4718-8fa1-cff3e0d4734d
Content-Type: application/json

### Login
POST {{host}}/api/v1/login
Content-Type: application/json

{
  "id": "20129b22-6dcb-4718-8fa1-cff3e0d4734d",
  "password": "123456"
}

### Search user
GET {{host}}/api/v1/user/search?first_name=Илья&last_name=Абрамов
Content-Type: application/json
